name: Notify Jenkins

on: 
  push:
    branches: ['main']

jobs:
  curl:
    name: Notify Jenkins Server
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@v1
        env:
          jenkins_server_ip: ${{ secrets.JENKINS_SERVER_IP }}
          authentication_token: ${{ secrets.AUTHENTICATION_TOKEN }}
          jenkins_username: ${{ secrets.JENKINS_USERNAME }}
          jenkins_password: ${{ secrets.JENKINS_PASSWORD }}
        with:
          args: |
            -u \"$jenkins_username:$jenkins_password\" \"http://$jenkins_server_ip/job/Dev%20-%20Frontend%20-%20Inhub%20Plateform/build?token=$authentication_token\"
